### ISSUE TITLE
Failed to select full amount

### ISSUE THREAD

**Issue by n0n0n0n0** [blocktrail/blocktrail-sdk-php#117]
I cant send full wallet balance and getting error:

A Server Error has occurred! Server Response: {"code":0,"msg":"Failed to select full amount"}

**Comment by bachvtuan** [comment]
Hi. I have some issue. Facing same on both web interface and API too.
Please fix.

**Comment by petermacel** [comment]
Hello, I see this error also today and cannot spend any btc from my account I have 2.5 BTC there and cannot send even 0.01 BTC. Still see the error "Failed to select full amount" 
How to get access to my bitcoins now?

**Comment by n0n0n0n0** [comment]
looks like after moving to btc.com they have decided to ruin it
