### ISSUE TITLE
 Error: Sorry, no new webhooks can be created at this time

### ISSUE THREAD

**Issue by HackinwaleDev** [blocktrail/blocktrail-sdk-php#134]
Below is my implementation of how I am setting up my webhook:

 `    setupWebhookForUser: (routeUrl, iReqId) => {
        return walletClient.setupWebhook( "https://routeUrl",  iReqId, (err, response) => {               
                if (err) {
                    console.log('==Error setting up the webhook==');
                    console.log(err);
                    return false;
                }
                console.log('==Webhook setup successfully==')
                return response;
        });
    }`

As I run this code I got an error logged and says "Sorry, no new webhooks can be created this time"
I am using the sdk from npm and it is testnet. I hope it is not the same with mainnet.
What is the fix please.  @rubensayshi @afk11

**Comment by afk11** [comment]
hi - neither myself or ruben work there anymore! unfortunately I can confirm the webhooks feature was removed several months ago.

**Comment by HackinwaleDev** [comment]
Thanks for your response @afk11 but could you recommend me an alternative wallet API that works perfect just like blocktrail.

I need it for my project which has been delayed for months just because of this API stuff.

**Comment by abgit** [comment]
https://developer.bitaps.com

**Comment by HackinwaleDev** [comment]
Thank you @abgit I am reading their documentation with wide smile on my face. Seems like kind of stuff I have been looking for :-D

I will close this issue once I get it work so i can recommend for others too.
Thanks again.

**Comment by abgit** [comment]
No problem.
I'm testing bitaps.com too.. and btw, i created a [simple php package](https://github.com/abgit/bitaps) to help me with that api.

**Comment by HackinwaleDev** [comment]
Good stuff! Would have love to check that out, ain't doing php but NodeJs. 

Btw what do you think about Cryptopay (https://developers.cryptopay.me/)?

**Comment by HackinwaleDev** [comment]
@abgit is it possible that the api does not work with nodejs? I asked because I have been trying to create a simple wallet but no response and no error log too just 304.

Thanks.

**Comment by lsgrep** [comment]
I think Thomas has answered your question. Closing this issue for now, and I sorry I do not know much about `bitaps`.  Please reopen if you have any questions

**Comment by HackinwaleDev** [comment]
Yea you can close. I am cool now with an alternative API :)
