### ISSUE TITLE
guzzlehttp/guzzle dependency update to ^6.1

### ISSUE THREAD

**Issue by abgit** [blocktrail/blocktrail-sdk-php#21]
Hi all,
Can you please turn sdk compatible with [latest stable guzzlehttp](https://github.com/guzzle/guzzle/releases/tag/6.1.1) ?

`guzzlehttp/guzzle ^6.1`

thanks
FA

**Comment by rubensayshi** [comment]
that's pending https://github.com/99designs/http-signatures-guzzlehttp/pull/8

**Comment by iwex** [comment]
And how long it will be pending? :)

**Comment by rubensayshi** [comment]
fixed in v2.1.0 release, keep in mind the BC breaks when upgrading from v1.x
