### ISSUE TITLE
$changeAddress not used in Wallet.php

### ISSUE THREAD

**Issue by Seagulls** [blocktrail/blocktrail-sdk-php#23]
`    /**
     \* create, sign and send a transaction
     *
     \* @param array     $outputs            [address => value, ] or [[address, value], ] or [['address' => address, 'value' => value], ] coins to send
     \*                                      value should be INT
     \* @param string    $changeAddress      change address to use (autogenerated if NULL)
     \* @param bool      $allowZeroConf
     \* @param bool      $randomizeChangeIdx randomize the location of the change (for increased privacy / anonimity)
     \* @param null|int  $forceFee           set a fixed fee instead of automatically calculating the correct fee, not recommended!
     \* @return string the txid / transaction hash
     \* @throws \Exception
     */

public function pay(array $outputs, $changeAddress = null, $allowZeroConf = false, $randomizeChangeIdx = true, $forceFee = null) `

$changeAddress is not used when building the transaction so it is impossible to specify the change address.

**Comment by rubensayshi** [comment]
fixed, will be in v3.x release
