### ISSUE TITLE
$client->subscribeAddressTransactions Not working

### ISSUE THREAD

**Issue by ParadoxalManiak** [blocktrail/blocktrail-sdk-php#40]
I'm currently testing this SDK to see if it will fit for my next project but it seems that the  `subscribeAddressTransactions` function is not working. 

Every time I'm calling it I get this message `The object you've tried to access does not exist.` and I know for sure that the `BTC Address` and the `Webhook Identifier` have been created before the call and are valid.

**Comment by rubensayshi** [comment]
we have tests running (and passing) `subscribeAddressTransactions`, 

can you paste the snippet of code that you're using? and maybe your webhook indentifier?  
if you wanna continue in private then you can also mail support@blocktrail.com

**Comment by ParadoxalManiak** [comment]
I'm getting this error
```bash
{"error":{"type":"Blocktrail\\SDK\\Connection\\Exceptions\\ObjectNotFound","message":"The object you've tried to access does not exist.","file":"\/var\/www\/vendor\/blocktrail\/blocktrail-sdk\/src\/Connection\/RestClient.php","line":336}}
```

And this is the code I'm using to test the SDK. The phpunit tests are passing but I cannot get this to work. Also is this the only way to make sure that the payment is good ? Checking the webhook event after payment ?

```php
$client  = new \Blocktrail\SDK\BlocktrailSDK($blockPay['key'], $blockPay['secret'], "BTC", true);
$wallet  = $client->initWallet($blockPay['wallet'], $blockPay['walletPassword']);

$address = $wallet->getNewAddress();
$webhookId = rand('999', '99999999');
$wallet->setupWebhook($reqUrl, $webhookId);
var_dump($client->subscribeAddressTransactions($webhookId, $address, $dbConfig['pay_btc_confirmations']));
```

**Comment by rubensayshi** [comment]
wallet webhooks automatically get all past and future generated addresses added to them, that's why it's not possible to manually add any addresses to them.

**Comment by ParadoxalManiak** [comment]
So what I should do ? How else I can get the events from only one address at a time ? I want to verify the payment from a user and make sure that they paid a certain amount, is there any other way to do this ?

**Comment by HackinwaleDev** [comment]
I have setup the webhook and when surprisingly when I test it I got an error that says:

Error: Sorry, no new webhooks can be created at this time.

This left me confused. I am using the testnet version of the api. What could be the way out. Kindly help.

Thanks.

**Comment by lsgrep** [comment]
Hi,  We no longer provide Webhooks service. Apologies for the inconveniences.
https://github.com/blocktrail/blocktrail-sdk-php/issues/134
