### ISSUE TITLE
Composer does not mention that CURL is required.

### ISSUE THREAD

**Issue by Elycin** [blocktrail/blocktrail-sdk-php#47]
While installing 3.0 from composer this morning, I've installed the PHP libraries as required listed in the readme, however under usage with laravel it was noted that I was missing php5-curl/php7.0-curl.
After adding the library via apt-get, my website resumed normal operation.

The package requirements for composer also does not mention that curl is needed.

Could it be listed that curl is also needed for future reference? I also don't know if anyone else has experienced it but I am rather certain due to my troubleshooting that missing curl was the cause.

Regards,
Andrew

**Comment by rubensayshi** [comment]
Hey Andrew,

sorry, I think we never really considering curl not being installed, 
thx for reporting this, I'll add it to composer.json and make sure it will be in the next release!

**Comment by Elycin** [comment]
No problem!
Thanks for an awesome API!
