### ISSUE TITLE
Add an interface class for overview

### ISSUE THREAD

**Issue by patricksavalle** [blocktrail/blocktrail-sdk-php#5]
May I suggest creating an Interface for the SDK class? It gives a quick overview of all API methods without have to read the entire Class.

    class BlocktrailSDK implements BlocktrailSDKinterface { ... }

**Comment by rubensayshi** [comment]
fixed in https://github.com/blocktrail/blocktrail-sdk-php/commit/951bb423c67a0c382c1ffcff61e491d9db49219f will create a new tagged release tomorrow
