### ISSUE TITLE
Import wallet to electrum

### ISSUE THREAD

**Issue by n0n0n0n0** [blocktrail/blocktrail-sdk-php#78]
How to import wallet to electrum? Are there any examples?

**Comment by afk11** [comment]
Since the wallet uses multisig, it's not really possible to import the wallet into electrum in a usable way. You should send your coins to a new electrum seed.

**Comment by n0n0n0n0** [comment]
So wallet can be used only via blocktrail service and if (hope not) it will close in future or smth will happen with it we'll lost our coins w/o any options to restore wallets? right?

**Comment by afk11** [comment]
No, you have it wrong. When you keep your backup PDF, you can recover your coins even if we close down. 

From a recovery standpoint, our wallets use their own scheme which you can 'backup from' easily, but wouldn't be accepted by other wallets. You could re-encode the seed and stuff for electrum, but, electrum won't be able to cosign with blocktrail/your second key, so how would it work anyways?

**Comment by rubensayshi** [comment]
https://github.com/blocktrail/wallet-recovery-tool

this tool will always let you recover your BTC, it has https://insight.bitpay.com/ builtin data source as fallback for if our servers are down.  

you can see a running version here; https://recovery.blocktrail.com  
which is hosted by github (using github pages).
